name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make
      
    - name: Test Colors
      run: ./test Color
      
    - name: Basic Image I/O Tests
      run: ./test basic
      
    - name: Test all scripts related to command x, where x is the command name
      run: ./test x
    
    - name: Test add functionality.
      run: ./test add
    
    - name: Show logs.
      run: cat ./test_log.txt
